services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - "3000:3000"
    # mounting . is causing seg-fault on macosx
    #volumes:
    #- .:/app
    depends_on:
      - solr
    # command: bundle exec rails server -b 0.0.0.0 -p 3000
    environment:
      - SOLR_URL # Set via environment variable or use default defined in .env file
      - SECRET_KEY_BASE
      - DATABASE_URL
    volumes:
      - sqlite3-data-blacklight-demo:/rails/storage

  solr:
    environment:
      - SOLR_PORT # Set via environment variable or use default defined in .env file
      - SOLR_VERSION # Set via environment variable or use default defined in .env file
      - SOLR_MODULES=analysis-extras
    image: "solr:${SOLR_VERSION}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8983/solr/blacklight-core/admin/ping || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - $PWD/solr/conf:/opt/solr/conf
    ports:
      - "${SOLR_PORT}:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"

volumes:
  sqlite3-data-blacklight-demo:
